### ISSUE TITLE
Next/Prev broken

### ISSUE THREAD

**Issue by SamWhited** [photoshell/photoshell#101]
The next/prev buttons appear to have been broken.

**Comment by campaul** [comment]
Do you have the latest version, because it's working fine for me.

**Comment by SamWhited** [comment]
Yah, I do; weird. I noticed it yesterday and forgot to make an issue. I'll see if I can't figure out what's different on my end after I eat.

**Comment by SamWhited** [comment]
No error on the console when you click the buttons either, for the record. I thin it's selecting the next image, but not redrawing.

**Comment by SamWhited** [comment]
Re-importing my library fixed it. Not sure what that was about.
