### ISSUE TITLE
Create magic self caching image thing

### ISSUE THREAD

**Issue by campaul** [photoshell/photoshell#137]
I want a wrapper/factory/subclass of GTK images that can handle things like intelligently caching itself and displaying a loading spinner while it's fetching image data. Vague idea but based on what I've been messing with tonight I think it's doable and fits the application architecture well.

**Comment by SamWhited** [comment]
Partially solved by #117; I think it makes more sense for the widget to display things like a spinner. On the other hand, a subclass of GTK image also might make sense for other things (the actual image loading / caching).

So the widget could be created and destroyed as views change, but the underlying image would be loaded up by each one and handles its own caching and the like.

**Comment by campaul** [comment]
The caching is now handled by the GtkImageCache, so all this needs to do is be smart enough to show a spinner until the image cache returns.

**Comment by campaul** [comment]
Since #117 can handle the spinner and #138 handled the caching, closing this as duplicate.
