### ISSUE TITLE
Should we populate missing config fields?

### ISSUE THREAD

**Issue by campaul** [photoshell/photoshell#142]
If you launch PhotoShell with a config that's empty or missing some fields, the missing fields will become the defaults, but those aren't written back out to the file. Should they be?

An argument for this: If we add a new field and the user updates, they wont know it exists because it will never show up in their config file as things currently are.

An argument against this: Why the hell did you change my config file!?

**Comment by SamWhited** [comment]
I think we should just ship a default config file with PS (installed by your friendly neighborhood package manager or integrated installation solution). We should never touch the config file (unless the user changes a value on a config screen).

**Comment by campaul** [comment]
This is actually a moot point. There is going to be a settings UI so the config should be invisible to all but advanced users. So in that case we may as well only touch it when the technical need arises.
