### ISSUE TITLE
Investigate rawpy

### ISSUE THREAD

**Issue by SamWhited** [photoshell/photoshell#153]
Instead of taking the time to turn rawphoto into a libraw wrapper, investigate using an existing wrapper (eg. [rawpy](https://pythonhosted.org//rawpy/api/index.html)).

I keep starting on the rawphoto work, and then realizing that it's pointless to have a pure-python fallback (as much as I don't like the idea of being dependant on libraw, our functionality is going to be severely limited if they don't have libraw installed). This means we'd probably have to drop support for everything but cpython (I think?), but for simplicities sake it might be a good idea.

Worth investigating the existing libraries anyways before we commit to writing our own wrapper.

**Comment by campaul** [comment]
rawpy's setup.py requires numpy, which makes it impossible to install using just requirements.txt. This makes it a non-starter in my opinion and is why I removed it in the first place. Also if I had to speculate that kind of issue is probably a warning sign off a systemic problem with how it's written. If we want his libraw bindings we're going to need to make our own.

**Comment by campaul** [comment]
*if you want good libraw bindings

Why can't comments be edited on the mobile site?

**Comment by campaul** [comment]
*if we want

Really, this is bad UI github.

**Comment by SamWhited** [comment]
> Why can't comments be edited on the mobile site?

That is deeply irritating.

>  if I had to speculate that kind of issue is probably a warning sign off a systemic problem with how it's written

Yup, I agree. Hadn't gotten as far as any of this yet (and didn't remember that we'd ever used it).

Looking for other alternatives (just in case), but I suspect that's the end of this issue.
