### ISSUE TITLE
Add a utility functions class

### ISSUE THREAD

**Issue by SamWhited** [photoshell/photoshell#75]
Things like `library.hash_file` should probably live in a utility function class instead of directly in the library (that one in particular has a TODO for this). I'm sure there are other places where this would be useful too.

**Comment by campaul** [comment]
A module makes more sense than a class, and I already added one, but from experience this is an anti-pattern. The `util` module turns into that junk drawer that everyone has in their kitchen and becomes the place everything gets shoved.

**Comment by SamWhited** [comment]
Makes sense.
