### ISSUE TITLE
Add class for managing sidecar files

### ISSUE THREAD

**Issue by SamWhited** [photoshell/photoshell#78]
Sidecar files should probably be spit into their own class. It will get unwieldy to work on them quickly as is.

**Comment by SamWhited** [comment]
We might also consider swapping to XMP files. As much as I hate XML based formats, XMP is more or less the industry standard (and would give us compatibility with Lightroom / Darktable libraries).

**Comment by campaul** [comment]
There is now the `Photo` class which abstracts away the sidecar files.

**Comment by campaul** [comment]
As a side note, this means we could completely change our sidecar format and nothing else in the app would need to know about it.
