### ISSUE TITLE
Possibly use a GNOME-style view switcher?

### ISSUE THREAD

**Issue by SamWhited** [photoshell/photoshell#79]
The GNOME design docs put view changing inside a [view switcher](https://developer.gnome.org/hig/stable/view-switchers.html.en) (pill buttons) in the center of the titlebar.

It probably doesn't really matter as the view switch buttons look good already, but we might consider it. The gnome design docs are pretty well thought out overall.

![https://developer.gnome.org/hig/stable/figures/patterns/patterns.svg](https://developer.gnome.org/hig/stable/figures/patterns/patterns.svg)

![https://developer.gnome.org/hig/stable/figures/patterns/view-switcher.svg](https://developer.gnome.org/hig/stable/figures/patterns/view-switcher.svg)

**Comment by SamWhited** [comment]
Actually, thinking about this more, I think the views we have (slideshow and grid) are more or less the same view as far as the "view switcher" widget would be concerned. They're both just different modes of "preview". Maybe the view switcher could be added when we add, eg. "export view" and "edit view" (or whatever we call them). Then again, maybe grid view will just *be* the default preview view (zooming all the way in could result in one full-window image, zooming out results in smaller and smaller thumbnails in a grid), and the slideshow view will eventually be just for actual slideshows? In this case, we could go ahead and do a view switcher (and replace the current view switch buttons with zoom buttons or something).

**Comment by campaul** [comment]
The difference between grid and slideshow mode right now is that slideshow loads a single full res image and grid loads in multiple preview sized images. Eventually slideshow is going to become the edit view where you can zoom and pan on a single photo you're editing and grid view will become the preview view where you can zoom in so you're only looking at one at a time, but they're still just previews.

As for how to switch views I support following the gnome docs as much as we can for that.

**Comment by SamWhited** [comment]
Sounds good; I'll assume they will remain two separate views then. Really, the docs are exactly what we have (just centered, and with text).

**Comment by campaul** [comment]
Also doing the grid view efficiently is non-trivial, so I've been using slideshow as the default preview mode until I get around to doing grid correctly. When we add text to them we should probably just make it say "Edit" and "Preview" since that's what they'll become.

**Comment by campaul** [comment]
Another note so we don't forget, the design docs have views going from broad to specific (from left to right) so we should probably swap the order of the buttons to make preview on the left.

**Comment by campaul** [comment]
Fixed by #92
