### ISSUE TITLE
Maybe commit the icon

### ISSUE THREAD

**Issue by campaul** [photoshell/photoshell#88]
It's small, not likely to change often, and it seems silly for inkscape to be a runtime dependency.

**Comment by SamWhited** [comment]
It shouldn't be a runtime dependency, just a compiletime one.

**Comment by SamWhited** [comment]
But yah, I don't see any problem with committing it alongside its sources. Do we want to actually use that one though? It doesn't show up very well when it gets small.

**Comment by campaul** [comment]
This can wait until we have a more finalized version of the icon, but eventually I want someone to be able to clone and do `make run` without having inkscape installed.

**Comment by SamWhited** [comment]
Yah, when you put it that way I guess "compile time" isn't really a thing with Python so much.
