### ISSUE TITLE
Support fullscreen mode

### ISSUE THREAD

**Issue by campaul** [photoshell/photoshell#89]
This at least works in Gnome, but it may be supported everywhere GTK3 is. Either way this we can never have too many available pixels for photo editing.

**Comment by SamWhited** [comment]
Confirmed, works in XFCE as well.

**Comment by campaul** [comment]
Calling the `fullscreen` method of the window puts it in fullscreen mode, but you don't get the drop-down header bar for free so there is no way to exit.

**Comment by SamWhited** [comment]
Related: #43

**Comment by campaul** [comment]
Fixed by #93
