### ISSUE TITLE
Hashing optimization

### ISSUE THREAD

**Issue by SamWhited** [photoshell/photoshell#96]
Working on returning metadata in rawphoto. One thing it would return is the hash which we'll use to identify the image later. That got me thinking about how we could speed up the hashing on slow machines.

Do we really need the hash for the entire file?

What if we checked if certain identifying metadata fields were present, and then just hashed the metadata and used that as the identifier? If those fields aren't present, only then do we hash the entire file.

The actual raw file should never change after it comes out of the camera, so I think this would work. Fields that we could look for include a combination of sequence number, unique identifier, datetime, etc. If we have a few mostly-unique items (sequence number may repeat, but pair it with datetime and we're good; multiple photos may be taken at the exact tame time, but add the camera's serial number and se can see that they were different, etc.), we just hash the metadata blob. Otherwise, we hash the entire file.

This would effectively change our storage method from hash's to UUIDs (which are still hashes, but we don't know of what necessarily).

Thoughts?

**Comment by campaul** [comment]
Based on what I was seeing last night the bottleneck wasn't the hashing function, it was loading the file over USB2. Since we have to do that anyway to develop the raw, any time lost hashing is gained back by dcraw getting to load the now cached file.

**Comment by SamWhited** [comment]
I think the file would still be cached (since we have to access the file and read a large chunk of it to get the metadata). If I can find my old netbook I'll run some actual tests to see if this does anything; I'm assuming that hashing thousands of 25 meg files will still be a lot slower than hashing thousands of 4k blobs (made that number up, probably less).

**Comment by campaul** [comment]
I don't think it will be enough faster to warrant the complexity. This will be something we have to special case for every raw format, and is more likely to break as parsing behavior is updated. File hashes have no real edge cases, we can work with them easily from outside the app, and they give us a mechanism for verifying file integrity for free if we ever want it.

**Comment by SamWhited** [comment]
Yah, after playing with it a bit (looking more at file read times on a slow drive than CPU), I don't think it's going to matter. Even my slowest drives are quick enough that it's hard to get any noticable speed increase from reading just the start of a file over the full thing on the initial pass. And you're right, the complexity is definitely not worth it (which is something I didn't even really consider, stupidly enough). Thanks.
